### ISSUE TITLE
[Feature] Allow CSP to be bypassed in webkit/browser context

### ISSUE THREAD

**Issue by tddebart** [shdwmtr/millennium#133]
### Before Requesting

- [X] I found no existing issue matching my feature request
- [X] This request is related to Millennium, and not a request for a specific theme/addon

### Describe the feature you'd like!

Currently if you want to do a fetch in the store/community hub window context you can't because of Steam's CSP blocking it.
SFP fixes this by running [Page.setBypassCSP](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-setBypassCSP) on the webkit pages.
So my request is if this can also be done in millennium or maybe some other way to communicate to the plugin from the store window context.
This would help a lot with my store enhancement plugins I'm trying to make.

This error can be easily triggered by calling fetch with any url that steam doesn't allow(see error image) and if you fetch from a plugin browser js you get the more detailed error as seen in the error image.

### Anything else?

Image of error:
![image](https://github.com/user-attachments/assets/3fa5488d-bfc0-4431-b828-dff8ae10d1b5)

**Comment by shdwmtr** [comment]
Millennium used to use that method, but has since been removed due to limitations in the browser space in Steam. Millennium uses a technique to intercept sources in the browser to load CSS/JS incredibly quick, which you would have probably noticed if your switching from SFP. Essentially, the CSS/JS would load before `Page.setBypassCSP` loads, so it wouldn't work. 

I've thought about a `Millennium` object in the JS, to communicate with the python backend, but this doesn't fix the issues with CSS not being able to make cross origin requests.

I'm still brainstorming on a solution as of right now.

**Comment by shdwmtr** [comment]
try this latest build: https://github.com/shdwmtr/millennium/actions/runs/12043783338

I may have come up with a proper solution.

**Comment by tddebart** [comment]
Just tested it, it work beautifully, thank you this is exactly what i needed.
Websites like google still can't be fetched but that's because of no Access-Control-Allow-Origin on their side. Probably not fixable but the steam CSP is now fully bypassed. 🎉 
I'll close this issue

**Comment by shdwmtr** [comment]
Also make sure to update `millennium-lib` NPM package or this new feature won't work

**Comment by tddebart** [comment]
oh sick, that webkit folder change is really nice. Now I don't have to copy the js files from the plugin to the steamui folder anymore and it sort of live updates (after refresh).
Bypassing cors by calling the backend is not something I had thought of, but it works perfectly. Thanks.
